"""User and conversation setup

Revision ID: 5f504d1e2116
Revises: 83971b542463
Create Date: 2025-12-03 15:36:32.144136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f504d1e2116'
down_revision: Union[str, Sequence[str], None] = '83971b542463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_flow', sa.String(length=50), nullable=False),
    sa.Column('current_step', sa.String(length=100), nullable=False),
    sa.Column('state_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pending_confirmation', sa.String(length=255), nullable=True),
    sa.Column('pending_entity_type', sa.String(length=50), nullable=True),
    sa.Column('pending_entity_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('session_started_at', sa.DateTime(), nullable=False),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_user_message', sa.Text(), nullable=True),
    sa.Column('last_bot_message', sa.Text(), nullable=True),
    sa.Column('message_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('nickname', sa.String(length=100), nullable=True))
    # Use server_default to populate existing rows, then remove default for new inserts
    op.add_column('user', sa.Column('onboarding_status', sa.String(length=50), nullable=False, server_default='pending'))
    op.add_column('user', sa.Column('onboarding_step', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('onboarding_completed_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('travel_mode_active', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user', sa.Column('current_trip_id', sa.UUID(), nullable=True))
    op.add_column('user', sa.Column('daily_summary_enabled', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('user', sa.Column('daily_summary_time', sa.Time(), nullable=True))
    op.add_column('user', sa.Column('budget_alerts_enabled', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('user', sa.Column('confirmation_reminders_enabled', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('user', sa.Column('whatsapp_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user', sa.Column('whatsapp_verified_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_whatsapp_interaction', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'user', 'trip', ['current_trip_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'last_whatsapp_interaction')
    op.drop_column('user', 'whatsapp_verified_at')
    op.drop_column('user', 'whatsapp_verified')
    op.drop_column('user', 'confirmation_reminders_enabled')
    op.drop_column('user', 'budget_alerts_enabled')
    op.drop_column('user', 'daily_summary_time')
    op.drop_column('user', 'daily_summary_enabled')
    op.drop_column('user', 'current_trip_id')
    op.drop_column('user', 'travel_mode_active')
    op.drop_column('user', 'onboarding_completed_at')
    op.drop_column('user', 'onboarding_step')
    op.drop_column('user', 'onboarding_status')
    op.drop_column('user', 'nickname')
    op.drop_table('conversation_state')
    # ### end Alembic commands ###
